### ISSUE TITLE
Platforms are disabled to be crawling

### ISSUE THREAD

**Issue by thenods** [i64/music-api-kr#2]
### Description
You should check **robots.txt** in platforms. They are **disabled** to be crawling.
I think that you should **change** your way to get music chart.

### Reference
https://www.melon.com/robots.txt
![image](https://user-images.githubusercontent.com/32844246/64932240-84f78580-d878-11e9-8705-e811ce28ab2a.png)

https://music.bugs.co.kr/robots.txt
![image](https://user-images.githubusercontent.com/32844246/64932248-96409200-d878-11e9-9641-91e4fef6f65f.png)

https://music.naver.com/robots.txt
![image](https://user-images.githubusercontent.com/32844246/64932296-da339700-d878-11e9-8cef-7a654a226213.png)

**Comment by i64** [comment]
Thank you for the first issue.

I already know the meaning and role of `robots.txt`, and I also know that `robots.txt` exists on the website. 
However, the usual limitation of `robots.txt` is to prevent crawling of search engine-based crawlers. Source code-based crawling is possible independent of `robots.txt`, and unless I distribute this project through APIs and real-time service, I think the conditions specified by `robots.txt` will not have the same effect as `the terms and conditions of use`. 

If I have to change the method of crawling, please let me know what your `the way` is.

For your information, this project plans to use an open-source project such as `selenium` to solve the problem as the `We're sorry but client doesn't work properly without JavaScript enabled. Please enable it to continue.` has been crawled because of a webpage distributed in languages such as Vue.js.

Thanks.

**Comment by thenods** [comment]
I know that you didn't make API or Service. You have contributed others with making crawling source code. `robots.txt` is like an ethical promise. Keeping promise is not required, and also It is not illegal. But I want you to keep that promise as a developer. Because they spent a lot of time for making service.

What I want to say, you should change the way to get data without crawling.
( or you can contact Platforms )
